import type { ConnectionState, EventHandler, PublishOptions, SocketClientEvents, SocketClientOptions } from "./types";
export declare class SocketClient {
    private readonly options;
    private ws;
    private state;
    private disposed;
    private userClosed;
    private reconnectAttempts;
    private connectPromise;
    private connectResolve;
    private connectReject;
    private connectTimer;
    private reconnectTimer;
    private connectionNonce;
    private readonly listeners;
    private readonly desiredRooms;
    private readonly activeRooms;
    private readonly pendingAcks;
    private readonly queuedPublishes;
    constructor(input: Partial<SocketClientOptions> & Pick<SocketClientOptions, "url">);
    get connectionState(): ConnectionState;
    on<K extends keyof SocketClientEvents>(event: K, handler: EventHandler<SocketClientEvents[K]>): () => void;
    off<K extends keyof SocketClientEvents>(event: K, handler: EventHandler<SocketClientEvents[K]>): void;
    connect(): Promise<void>;
    disconnect(code?: number, reason?: string): void;
    dispose(): void;
    subscribe(room: string, signal?: AbortSignal): Promise<void>;
    unsubscribe(room: string, signal?: AbortSignal): Promise<void>;
    publish(room: string, event: string, payload: unknown, options?: PublishOptions): Promise<void>;
    private sendWithAck;
    private waitForAck;
    private removePendingAck;
    private resolvePendingAck;
    private rejectAllPendingAcks;
    private resubscribeAndFlush;
    private handleMessage;
    private validateEnvelope;
    private sendRaw;
    private enqueuePublish;
    private scheduleReconnect;
    private failConnect;
    private resolveConnect;
    private rejectConnect;
    private resetConnectPromiseState;
    private clearConnectTimer;
    private clearReconnectTimer;
    private safeCloseSocket;
    private setState;
    private emit;
    private validateOptions;
    private validateUrl;
    private assertRoom;
    private assertNonEmpty;
    private assertNotDisposed;
}
